#Deploy using SSH Remote command appleboy/ssh-action@master
#https://blog.soshace.com/deploying-your-nodejs-code-to-a-server-every-time-you-push-with-github-actions/
#https://github.com/marketplace/actions/ssh-remote-commands

name: Deploy using SSH
on:
  push:
    branches:
      - master
env:
  host: 3.93.192.55
  username: ubuntu
jobs:
  run_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: run ssh deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.93.192.55
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          script: |
           mkdir -p ~/new_calculator
           cd /home/ubuntu/lockr/github
           git clone git@github.com:AhmedELShafaie/calculator.git mycal-$(date +%m%d%Y)          




